apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: product-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
