---
extends: default
rules:
  document-start: disable
  line-length:
    max: 200
  indentation:
    spaces: 2
    indent-sequences: consistent
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  empty-lines:
    max: 2
  comments:
    min-spaces-from-content: 1
